<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Time Picker</name>
   <tag></tag>
   <elementGuidId>6892d661-e2ec-4072-9ddc-001452301f63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Time'])[1]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.timePicker-openIcon.display</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c4ee317-e7f8-4c3d-84ba-b67d5f04042b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>63f0d49c-3ee4-4c3b-a9cc-eec177e011e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>timePicker-openIcon display</value>
      <webElementGuid>0f75e09a-ccec-4a00-b920-aebb3854ea3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>72:2309;a</value>
      <webElementGuid>b3bc0249-5957-4de5-9126-eaa6e3a75230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>f0b89b6e-26d4-4378-b22b-f533edc45db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Time Picker</value>
      <webElementGuid>32668e31-738d-4cfb-b492-77c9bf0ff392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8:2309;a&quot;)/div[@class=&quot;slds-form form-horizontal slds-is-editing&quot;]/div[@class=&quot;slds-grid slds-gutters_small full cols-2 forcePageBlockSectionRow&quot;]/div[@class=&quot;slds-grid slds-col slds-is-editing slds-has-flexi-truncate full forcePageBlockItem forcePageBlockItemEdit&quot;]/div[@class=&quot;slds-form-element slds-hint-parent&quot;]/div[@class=&quot;slds-form-element__control&quot;]/fieldset[@class=&quot;uiInput uiInputDateTime uiInput--default uiInput--input uiInput--datetime&quot;]/div[@class=&quot;form--stacked form-element__group&quot;]/div[@class=&quot;dateTime-inputTime form-element form-element__control&quot;]/div[@class=&quot;input-has-icon input-has-icon--right&quot;]/a[@class=&quot;timePicker-openIcon display&quot;]</value>
      <webElementGuid>f08b04a3-0724-4a61-a1c2-c88639db2e41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time'])[1]/following::a[1]</value>
      <webElementGuid>4ba634e3-4dfb-4cbb-8185-59620c8f9a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Picker'])[1]/following::a[1]</value>
      <webElementGuid>05b9f5a4-0c05-48ba-bb43-0ceba643080b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appointment Number'])[2]/preceding::a[1]</value>
      <webElementGuid>bd988092-969b-48ac-a47d-ae10cffa53c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'Time Picker' or . = 'Time Picker')]</value>
      <webElementGuid>cfe28b1e-b2b0-401a-ba24-e72da8cad539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='8:2309;a']/div/div[2]/div/div/div/fieldset/div/div[2]/div/a</value>
      <webElementGuid>b7eedf8a-1ce1-4cf7-8e70-2f7ed2f4245d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[39]</value>
      <webElementGuid>a65bc99a-7796-42aa-8b1c-151c863665e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[2]/div/a</value>
      <webElementGuid>c0541c51-db9d-4a20-8703-101efd2fd359</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
