<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_1100 AM</name>
   <tag></tag>
   <elementGuidId>3b780586-112a-48c6-a5e1-b4085d04ec65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = '1100' and (text() = '11:00 AM' or . = '11:00 AM')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4348e80d-8c3e-4b5c-a3b4-3d4c802d830e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hours</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>38389e7b-8623-4704-94c3-e426e03e421d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>29acc854-bc0b-475c-8552-38568e11221a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>1471b5eb-b724-430e-b7d3-11222bb7a479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-minutes</name>
      <type>Main</type>
      <value>00</value>
      <webElementGuid>0e7aefb3-0f04-4729-b8fa-a6ea3fb8d90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1100</value>
      <webElementGuid>7d06d568-d535-4721-b104-4e382bf151bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11:00 AM</value>
      <webElementGuid>6e66602d-b71d-40b4-9207-c4bdc29403b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1100&quot;)</value>
      <webElementGuid>4c15c61f-9ee8-405f-af26-ab67cefd4309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '1100', '&quot;', ')')])[1]/following::li[23]</value>
      <webElementGuid>b65dec4a-7c9d-4ad7-9113-5c8973ad2b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[4]/following::li[23]</value>
      <webElementGuid>a02a35d2-e940-4485-966d-254f9fa95436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='11:00 AM']/parent::*</value>
      <webElementGuid>a8956283-d5f2-4747-810b-05d5432a7545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '1100' and (text() = '11:00 AM' or . = '11:00 AM')]</value>
      <webElementGuid>ce004342-4c80-4cdd-a3a0-a78ba2071e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='1100']</value>
      <webElementGuid>7e9749d6-645d-4b72-878a-c9f5e7a41e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3720:0']/div/ul/li[23]</value>
      <webElementGuid>dd359b4c-c55d-46ac-b68f-620c9164c03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[23]</value>
      <webElementGuid>a577de2b-32d0-436b-9ff7-047e0ba73fba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
