<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_31</name>
   <tag></tag>
   <elementGuidId>bfec14c5-4770-4122-9f44-23fa303452fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='SAT'])[1]/following::span[34]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1baa92e5-b6b5-434c-9a45-1200241f0657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-day weekday DESKTOP uiDayInMonthCell--default</value>
      <webElementGuid>f027ae3d-0c40-401e-bf18-04b61a6fe775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>3633:0</value>
      <webElementGuid>635e81be-3b36-4128-a9f8-3160376e40c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-class</name>
      <type>Main</type>
      <value>uiDayInMonthCell--default</value>
      <webElementGuid>42a8bad9-0411-4d47-8791-f0ff529c3761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>2ca6d3b4-ab22-43d2-9ad9-36f26d4578e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3427:0&quot;)/div[@class=&quot;scroller slds-datepicker&quot;]/div[@class=&quot;uiDatePickerGrid--default uiDatePickerGrid&quot;]/table[@class=&quot;calGrid&quot;]/tbody[1]/tr[@class=&quot;calRow&quot;]/td[@class=&quot;uiDayInMonthCell&quot;]/span[@class=&quot;slds-day weekday DESKTOP uiDayInMonthCell--default&quot;]</value>
      <webElementGuid>76a0d44b-d218-46c5-be5f-4c4cc81825e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAT'])[1]/following::span[34]</value>
      <webElementGuid>87b3491b-1fe0-4890-8ae4-7e05d6bc0b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FRI'])[1]/following::span[34]</value>
      <webElementGuid>6bb224d1-10ef-41b4-aa9c-eb057d3f0592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::span[9]</value>
      <webElementGuid>cd54c969-dbf7-406d-bb86-c2c5952ef35a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='31']/parent::*</value>
      <webElementGuid>9a65482a-e873-4f91-b149-9f2d00c88b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '31' or . = '31')]</value>
      <webElementGuid>0297198c-ff4a-41e1-892e-3ee33efd439c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3427:0']/div/div[2]/table/tbody/tr[5]/td[6]/span</value>
      <webElementGuid>d9121db2-1855-45df-98ec-23dccbe8b26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[6]/span</value>
      <webElementGuid>60676c33-4f16-49cf-b7e1-55aa47117303</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
